/*
 * SPDX-FileCopyrightText: Copyright Corsinvest Srl
 * SPDX-License-Identifier: GPL-3.0-only
 */

namespace Corsinvest.VisualStudio.Agents.Contracts;

// FromWebView wire DTOs (WebView → host C#) — the payloads WebViewMessageHandler.Handle
// receives. Two kinds: ...Request (correlated — the WebView awaits a response) and
// ...Notification (fire-and-forget). The shape ORIGINATES in TS (the sendRequest /
// sendNotification call sites); these classes mirror it so the handler can do
// `data.ToObject<XxxRequest / XxxNotification>()` instead of loose `data.Val(...)`. camelCase
// JSON keys map to these PascalCase props (Newtonsoft deserialization is case-insensitive).
// Fields the CLI owns (tool args, PermissionUpdate, attachments) stay `object`/`object[]` —
// same rule as ToolPermissionNotification.Input. TS interfaces generated by TypeGen; the
// opposite direction lives in ToWebViewDtos.cs.

/// <summary>Submit a prompt (cli_send_prompt): the composed text + client uuid for the
/// echoed bubble. attachments is the raw upload list (opaque; turned into CLI content
/// blocks by BuildContentBlocks), so it stays untyped.</summary>
public class SendPromptNotification
{
    public string Text { get; set; }
    public string Uuid { get; set; }
    public object Attachments { get; set; }
}

/// <summary>Answer a tool-permission request (cli_respond_permission). updatedInput /
/// updatedPermissions are opaque CLI structures (tool args / PermissionUpdate, snake_case)
/// passed straight back to the CLI, so they stay untyped.</summary>
public class RespondPermissionNotification
{
    public string ToolUseId { get; set; }
    public bool Allowed { get; set; }
    public string DenyMessage { get; set; }
    public object UpdatedInput { get; set; }
    public object UpdatedPermissions { get; set; }
}

/// <summary>Eye-toggle: flip this session's send-selection (cli_set_send_selection).</summary>
public class SetSendSelectionNotification
{
    public bool Enabled { get; set; }
}

/// <summary>Open a file in the editor at a line range (open_ide_file).</summary>
public class IdeFileNotification
{
    public string FilePath { get; set; }
    public int StartLine { get; set; }
    public int EndLine { get; set; }
}

/// <summary>Open a file at an edit site (open_ide_file_at_edit): when startLine is 0 the
/// host locates the range by matching oldString. newString is sent by the WebView but not
/// used host-side (kept so the payload type matches what's posted).</summary>
public class IdeFileAtEditNotification
{
    public string FilePath { get; set; }
    public int StartLine { get; set; }
    public int EndLine { get; set; }
    public string OldString { get; set; }
    public string NewString { get; set; }
}

/// <summary>Query for @-mention file/dir suggestions (file_get_suggestions).</summary>
public class GetSuggestionsRequest
{
    public string Query { get; set; }
}

/// <summary>Open a tool's full input/output in a temp doc (open_tool_output). which is
/// "in"|"out"; agentId routes the lookup to a sub-agent transcript when set.</summary>
public class ToolOutputNotification
{
    public string ToolUseId { get; set; }
    public string Title { get; set; }
    public string Which { get; set; }
    public string AgentId { get; set; }
    public string ToolName { get; set; }
}

/// <summary>Fetch a sub-agent's full transcript on expand (chat_get_subagent). sessionId
/// optional (falls back to the client's current session).</summary>
public class GetSubagentRequest
{
    public string AgentId { get; set; }
    public string SessionId { get; set; }
    // True → the WebView wants only the last ≤PreviewLines rows (chevron expand); false/absent → the
    // whole transcript (Show all).
    public bool Preview { get; set; }
}

/// <summary>Lazily fetch a stripped image's bytes (chat_get_image). sessionId is optional
/// (falls back to the client's current session). BlockIdx defaults to -1 so an absent value
/// fails the >= 0 guard, matching the old data.Val default.</summary>
public class GetImageRequest
{
    public string Uuid { get; set; }
    public int BlockIdx { get; set; } = -1;
    public string SessionId { get; set; }
}

/// <summary>Lazily fetch a compaction's full summary on expand (chat_get_compact_summary).
/// sessionId is optional (falls back to the client's current session).</summary>
public class GetCompactSummaryRequest
{
    public string SessionId { get; set; }
    public string Uuid { get; set; }
}

/// <summary>Cancel one running sub-agent by task id (chat_subagent_cancel).</summary>
public class SubagentCancelNotification
{
    public string TaskId { get; set; }
}

/// <summary>Load a page of transcript history (chat_get_history). beforeOffset = -1 for
/// the initial page, else the byte offset to page older content above (default -1 so an
/// absent value behaves like the initial page, matching the old data.Val default).</summary>
public class GetHistoryRequest
{
    public string SessionId { get; set; }
    public long BeforeOffset { get; set; } = -1;
}

/// <summary>Fetch account &amp; usage for the Account/Usage dialog (chat_get_usage). Empty
/// payload — the request carries no params, only correlates a response.</summary>
public class GetUsageRequest
{
}

/// <summary>Fetch the current session's context-window breakdown for the Context dialog
/// (chat_get_context_usage). Empty payload — correlates a response only.</summary>
public class GetContextUsageRequest
{
}

/// <summary>Fetch aggregated usage statistics for the Statistics dialog (chat_get_stats).</summary>
public class GetStatsRequest
{
    public StatsScopeDto Scope { get; set; } = StatsScopeDto.All;
    public StatsRangeDto Range { get; set; } = StatsRangeDto.All;
}

/// <summary>Open a stripped document block in a temp file (chat_open_document). BlockIdx
/// defaults to -1 so an absent value fails the >= 0 guard, matching the old data.Val default.</summary>
public class OpenDocumentNotification
{
    public string Uuid { get; set; }
    public int BlockIdx { get; set; } = -1;
    public string SessionId { get; set; }
}

/// <summary>Open a composer attachment in a temp file (open_chat_attachment). The bytes travel
/// inline because an attachment being composed lives only in WebView memory — the File API
/// never exposes its path, for drag-drop, paste or the file picker alike.</summary>
public class OpenAttachmentNotification
{
    public string Name { get; set; }
    public string Base64 { get; set; }
    public string MediaType { get; set; }
}

/// <summary>Show the VS diff dialog for a proposed edit (open_diff_dialog).</summary>
public class DiffDialogNotification
{
    public string FilePath { get; set; }
    public string OldString { get; set; }
    public string NewString { get; set; }
}

/// <summary>Hot-swap the permission mode (cli_set_permission_mode).</summary>
public class SetPermissionModeNotification
{
    public string Mode { get; set; }
}

/// <summary>Hot-swap the active model (cli_set_model). Empty model clears the override.</summary>
public class SetModelNotification
{
    public string Model { get; set; }
}

/// <summary>Toggle Thinking → runtime set_max_thinking_tokens (cli_set_max_thinking_tokens).
/// Display is null on OFF.</summary>
public class SetMaxThinkingTokensNotification
{
    public int MaxThinkingTokens { get; set; }
    public string Display { get; set; }
}

/// <summary>Fork the session before a message (session_fork): new JSONL truncated at
/// messageUuid, opened in its own pane. sessionId optional (falls back to current).</summary>
public class ForkNotification
{
    public string MessageUuid { get; set; }
    public string SessionId { get; set; }
}

/// <summary>Open an external URL in the default browser (open_external_url).</summary>
public class ExternalUrlNotification
{
    public string Url { get; set; }
}
